### ISSUE TITLE
[skipjack] no vibration

### ISSUE THREAD

**Issue by megamaced** [AsteroidOS/meta-smartwatch#100]
The vibration on notifications seems to have stopped working in the most recent nightlies

**Comment by megamaced** [comment]
ah just saw https://github.com/AsteroidOS/meta-asteroid/pull/102

Will test again in the latest nightly

**Comment by docgalaxyblock** [comment]
Hey @megamaced is it now working?

**Comment by beroset** [comment]
Tested on `skipjack` just now and it works.

**Comment by MagneFire** [comment]
@beroset Thanks for confirming. Closing the issue.
@megamaced feel free to open this issue again if the issue arises again.
