### ISSUE TITLE
[beluga] No audio drivers

### ISSUE THREAD

**Issue by MagneFire** [AsteroidOS/meta-smartwatch#131]
The kernel drivers for the audio subsystem isn't packaged in the kernel. Instead they are available under a different repository: https://android.googlesource.com/kernel/msm-extra/+/refs/heads/android-msm-beluga-4.9-pie-wear-mr2.
The compiled kernel modules are located on the `vendor` partition, but these cannot be loaded since they mismatch due to kernel configuration changes. We should find a way to compile these kernel modules as well. Probably by means of a separate recipe.

**Comment by wannaphong** [comment]
sound: https://android.googlesource.com/kernel/msm/+/refs/heads/android-msm-beluga-4.9-pie-wear-mr2/sound/
wifi: https://android.googlesource.com/kernel/msm-modules/wlan/+/refs/heads/android-msm-beluga-4.9-pie-wear-mr2
