### ISSUE TITLE
[Sturgeon] Display Settings: Burn in Protection is always enabled

### ISSUE THREAD

**Issue by araccaine** [AsteroidOS/meta-smartwatch#133]
Watch: Huawai (sturgeon)
Asteroid Version: 1.1-nightly build 20221119150145
Kernel Version 3.10.40

My watch does not respect the display setting "Burn in protection". It is always enabled.

**Comment by MagneFire** [comment]
Thanks for reporting your issue!
I've already identified the issue and a pull request is ready to be merged. Once reviewed it should be fixed in the next nightly.
