### ISSUE TITLE
[Beluga/OW19W8] Oppo Watch Found Bugs/issues/missing software features on clean/default install

### ISSUE THREAD

**Issue by NickTheOnlyNeko** [AsteroidOS/meta-smartwatch#232]
**Missing Features:**
-  **1st:** WiFi access or at least an App for Accessing WiFi Settings(Not that WiFi is needed but it would be a nice "Plus" to have). 
-  **2nd:** Needs added security (In example a Pin Code, Figure or Password) against theft.
-  **3rd:** "Show Touch" feature would be a good "Plus" to have for people with big hands and fingers.
-  **4th:** Power Saver mode, but it's being worked on in [#146](https://github.com/AsteroidOS/meta-smartwatch/issues/146) so i won't complain or comment on that because the person who's working on it is doing a good job on reverse engeneering and documentating their process and progress.
-  **5th:** Customization app/option for the extra/misc button.
-  **6th:** THIS IS ONLY FOR THE LTE(WITH SIM CARD) VERSION, would be nice to have a "Track smart watch location Through Mobile Data" option/app.
-  **7th:** An app on the watch to send music files or photos from a phone to the watch. 

**Broken Features:** 
-  **1st:** Screen doesn't go 100% Off / 100% Dark even tho I've set the "Always on Display" setting to Off (Edit it mysteriously fixed it's self, I have no idea how). 
-  **2nd:** One of the watch faces has it's "Seconds" hand missing(Probably a GUI/Graphics issue). 
-  **3rd:** The heart beat sensor isn't being used at all by the default app and i know that it's not working because it's somehow measuring a pulse while the smart watch is being set on a desk that has 0 pulse/heart beat.
-  **4th:** The Alarm works but without any sound or noise, soo if you're a heavy sleeper good luck on your appointment because you ain't going anywhere except your bed and sleeping night night wonderland.

**100% Working Features:** 
-  **1st:** The Light Sensor works.
-  **2nd:** Tilt to wake works.
-  **3rd:** Touch works.
-  **4th:** Bluetooth works.
-  **5th:** Vibration works. 
-  **6th:** Flashlight app works.

**Suggestion for more/new Features**(could be considered as bloat but i feel like those should come pre-installed because they are "nice to have" features that i used to have and use on Wear OS) : 
-  **1st:** NFC Reader/Cloning+Emulating app/feature so users could store their NFC Debit Card info and their NFC Door Keys. 
-  **2nd:** QR/Bar Code storing app (alternative to "One Wallet"). 
-   **3rd:** A proper normal calendar app. (Like no fancy sh#t just a regular normal calendar app that shows the month and days+day/date and the ability to preview the upcoming months.) 

**Unsure sure Features:**
-  **1st:** The rest of the hardware features are untested or unknown to be working or not. 

all in all it just needs a tiny little bit more polishing and it would be a good alternative for the Oppo Watch because it has reached EOLS(**E**nd **O**f **L**ife **S**upport)

**(P.S some of the comments were made in a Humorous way/manner so please don't take it personally and just have a laugh or two)**

**Comment by beroset** [comment]
With 14 different issues in one report, it makes it difficult to track.  Many of these are duplicate issues.  Also, I'm not sure what you mean in your 3rd feature request.  Maybe you can draw and paste a picture of what you have in mind?

**Comment by NickTheOnlyNeko** [comment]
> With 14 different issues in one report, it makes it difficult to track. Many of these are duplicate issues. Also, I'm not sure what you mean in your 3rd feature request. Maybe you can draw and paste a picture of what you have in mind?

something like this, of course this style of calendar is from the Cinnamon DE for linux but you get the jist
![image](https://github.com/AsteroidOS/meta-smartwatch/assets/76766408/43d0290d-e7f8-44e3-93a7-b9cf59f83aa4)

**Comment by NickTheOnlyNeko** [comment]
> > With 14 different issues in one report, it makes it difficult to track. Many of these are duplicate issues. Also, I'm not sure what you mean in your 3rd feature request. Maybe you can draw and paste a picture of what you have in mind?
> 
> something like this, of course this style of calendar is from the Cinnamon DE for linux but you get the jist ![image](https://user-images.githubusercontent.com/76766408/283244098-43d0290d-e7f8-44e3-93a7-b9cf59f83aa4.png)

basically use the "KISS" rule "Keep It Simple (and) Stupid"

**Comment by NickTheOnlyNeko** [comment]
> With 14 different issues in one report, it makes it difficult to track. Many of these are duplicate issues. Also, I'm not sure what you mean in your 3rd feature request. Maybe you can draw and paste a picture of what you have in mind?

also the whole thing is as an external/3rd party and free "QA Service"

**Comment by beroset** [comment]
Since almost all of these are duplicates of existing issues, I'd suggest that you close this and replace it with a single topic issue regarding the calendar.  Also keep in mind that the screen of a watch is much smaller than that of a phone.  If you're already concerned about the difficulties faced by "people with big hands and fingers" consider that the calendar display you show is going to be really difficult to both see (for those who don't have great vision) and to use (for those of us with big fingers).  By creating a single-issue issue instead, it's much more likely to get attention and action.  Thanks!

**Comment by NickTheOnlyNeko** [comment]
> Since almost all of these are duplicates of existing issues, I'd suggest that you close this and replace it with a single topic issue regarding the calendar.  Also keep in mind that the screen of a watch is much smaller than that of a phone.  If you're already concerned about the difficulties faced by "people with big hands and fingers" consider that the calendar display you show is going to be really difficult to both see (for those who don't have great vision) and to use (for those of us with big fingers).  By creating a single-issue issue instead, it's much more likely to get attention and action.  Thanks!

I mean for the calendar it could be "Gesture and/or Arrows" navigation for scrolling through months, i don't know what else would you want to do in an calendar app other than doing your Agenda but you have an Agenda app already so it makes not alot of sence
