### ISSUE TITLE
[lenok] Nightlies stuck at boot since 2024-02-16

### ISSUE THREAD

**Issue by bigoulours** [AsteroidOS/meta-smartwatch#240]
Hi all,

first, thank you for the great work you're doing here.
I just got my hands on a lenok and the installation took me some time since the newest nightlies stay stuck at boot.
The problem seems to have appeared with version 2024-02-16. I'm able to install 2024-02-09 and older.

Cheers,

**Comment by eLtMosen** [comment]
Thanks for the heads up! The issue was identified today. We shipped the qemu default.config instead of the device specific one.
That has been fixed and next nightlies should work again!
