### ISSUE TITLE
List Support TicWatch C2 (Not C2+)

### ISSUE THREAD

**Issue by wannaphong** [AsteroidOS/meta-smartwatch#44]
This list from my testing.

- [x] Display
- [x] Touch
- [ ] Microphone
- [x] Bluetooth AsteroidOS/meta-smartwatch#43
- [ ] GPS
- [ ] NFC
- [ ] WLAN
- [x] Heart Rate
- [x] Tilt-to-Wake
- [x] Haptics
- [x] USB

**Comment by eLtMosen** [comment]
TicWatch C2/C2+/S2 and E2 are now listed on the install pages.
