### ISSUE TITLE
G Urbane continually boots into fastboot despite nominally 'successful' install

### ISSUE THREAD

**Issue by captain-veidt** [AsteroidOS/meta-smartwatch#49]
Installation process seems to silently fail, regardless of distinct downloads of relevant files to account for minor download failures. Instructions from [relevant page here](https://asteroidos.org/install/bass/) followed. Attached is my CLI output without any failures. 
![urbane](https://user-images.githubusercontent.com/100708931/156205330-ce6aff07-48c3-4e13-9ee9-941656a9f341.png) Referencing the troubleshooting page [here](https://asteroidos.org/wiki/boot-process/#troubleshooting), I've not yet seen the AsteroidOS splash come up even once, suggesting that I'm not able to offer any logs of failed boot processes. 
 
What's my next step here?

**Comment by eLtMosen** [comment]
Added advise to try multiple flashes to the new "Install Troubleshoot" section. 
That should solve this issue, whiich is very likely related to connection problems.
https://github.com/AsteroidOS/asteroidos.org/pull/227
