### ISSUE TITLE
Make sensors work

### ISSUE THREAD

**Issue by atx** [AsteroidOS/meta-smartwatch#55]
The connected sensors are described in [sensor_def_lenok.conf](https://p.atx.name/yvhekm2mn7). However, they are not connected directly to the ARM core, but instead to the Hexagon DSP coprocessor.

The kernel loads the (full of debug printf strings!) firmware to the coprocessor from `/system/vendor/firmware/adsb.*`, and then setups several /dev files which are presumably used by the original Android code to interface with the coprocessor using [FastRPC](https://developer.qualcomm.com/blog/how-use-fastrpc-offload-cpu-qualcomm-hexagon-dsp).

The /dev/adsprpc-smd ioctls are described in [the kernel documentation](https://android.googlesource.com/kernel/msm/+/android-msm-flo-3.4-kitkat-mr1/Documentation/arm/msm/adsprpc-drv.txt). What is missing is description of the RPC methods provided by the LG code.

These could likely be reverse engineered by statically analyzing the [DSP firmware](https://github.com/programa-stic/hexag00n) or by stracing ioctl calls in Android.

**Comment by docgalaxyblock** [comment]
Any news on this issues state?
My watches sensors are working

Are @GeckoEidechse problems resolved (somewhere else)?

lenok build 19.9.'22
---
<details><summary><code>test_sensors</code></summary><pre><code>
Hardware module ID: sensors
Hardware module Name: QTI Sensors Module
Hardware module Author: Qualcomm Technologies, Inc.
Hardware module API version: 0x1
Hardware HAL API version: 0x100
Poll device version: 0x1030001
API VERSION 0.1 (legacy): 0x1
API VERSION 0.1: 0x65537
API VERSION 1.0: 0x16777217
API VERSION 1.1: 0x16842753
API VERSION 1.2: 0x16908289
API VERSION 1.3: 0x16973825
API VERSION 1.4: 0x17039361
Got 33 sensors

=== Sensor 0 ==
Name: MPU6515 Accelerometer
Vendor: InvenSense
Version: 0x1
Handle: 0x0
Type: 1
maxRange: 19.613296
resolution: 0.595
power: 0.400000 mA
minDelay: 5000

=== Sensor 1 ==
Name: AK8963 Magnetometer
Vendor: AKM
Version: 0x1
Handle: 0xa
Type: 2
maxRange: 4911.999511
resolution: 0.149536
power: 5.0 mA
minDelay: 16666

=== Sensor 2 ==
Name: AK8963 Magnetometer Uncalibrated
Vendor: AKM
Version: 0x1
Handle: 0xb
Type: 14
maxRange: 4911.999511
resolution: 0.149536
power: 5.0 mA
minDelay: 16666

=== Sensor 3 ==
Name: MPU6515 Gyroscope
Vendor: InvenSense
Version: 0x1
Handle: 0x2
Type: 4
maxRange: 34.906585
resolution: 0.1068
power: 3.200000 mA
minDelay: 5000

=== Sensor 4 ==
Name: MPU6515 Gyroscope Uncalibrated
Vendor: InvenSense
Version: 0x1
Handle: 0x8
Type: 16
maxRange: 34.906585
resolution: 0.1068
power: 3.200000 mA
minDelay: 5000

=== Sensor 5 ==
Name: HSPPAD038 Pressure
Vendor: ALPS ELECTRIC CO.,
Version: 0x1
Handle: 0x3
Type: 6
maxRange: 1100.0
resolution: 0.13122
power: 1.500000 mA
minDelay: 11111

=== Sensor 6 ==
Name: MPU6515 Accelerometer -Wakeup Secondary
Vendor: InvenSense
Version: 0x1
Handle: 0x17
Type: 1
maxRange: 19.613296
resolution: 0.595
power: 0.400000 mA
minDelay: 5000

=== Sensor 7 ==
Name: AK8963 Magnetometer -Wakeup Secondary
Vendor: AKM
Version: 0x1
Handle: 0x20
Type: 2
maxRange: 4911.999511
resolution: 0.149536
power: 5.0 mA
minDelay: 16666

=== Sensor 8 ==
Name: AK8963 Magnetometer Uncalibrated -Wakeup Secondary
Vendor: AKM
Version: 0x1
Handle: 0x21
Type: 14
maxRange: 4911.999511
resolution: 0.149536
power: 5.0 mA
minDelay: 16666

=== Sensor 9 ==
Name: MPU6515 Gyroscope -Wakeup Secondary
Vendor: InvenSense
Version: 0x1
Handle: 0x19
Type: 4
maxRange: 34.906585
resolution: 0.1068
power: 3.200000 mA
minDelay: 5000

=== Sensor 10 ==
Name: MPU6515 Gyroscope Uncalibrated -Wakeup Secondary
Vendor: InvenSense
Version: 0x1
Handle: 0x1e
Type: 16
maxRange: 34.906585
resolution: 0.1068
power: 3.200000 mA
minDelay: 5000

=== Sensor 11 ==
Name: HSPPAD038 Pressure -Wakeup Secondary
Vendor: ALPS ELECTRIC CO.,
Version: 0x1
Handle: 0x1a
Type: 6
maxRange: 1100.0
resolution: 0.13122
power: 1.500000 mA
minDelay: 11111

=== Sensor 12 ==
Name: Gravity
Vendor: QTI
Version: 0x2
Handle: 0x24
Type: 9
maxRange: 19.613296
resolution: 0.595
power: 3.599990 mA
minDelay: 5000

=== Sensor 13 ==
Name: Linear Acceleration
Vendor: QTI
Version: 0x2
Handle: 0x25
Type: 10
maxRange: 19.613296
resolution: 0.595
power: 3.599990 mA
minDelay: 5000

=== Sensor 14 ==
Name: Rotation Vector
Vendor: QTI
Version: 0x2
Handle: 0x2b
Type: 11
maxRange: 1.0
resolution: 0.0
power: 8.599990 mA
minDelay: 5000

=== Sensor 15 ==
Name: Step Detector
Vendor: QTI
Version: 0x2
Handle: 0x32
Type: 18
maxRange: 1.0
resolution: 1.0
power: 0.399993 mA
minDelay: 0

=== Sensor 16 ==
Name: Step Counter
Vendor: QTI
Version: 0x2
Handle: 0x33
Type: 19
maxRange: 1.0
resolution: 1.0
power: 0.399993 mA
minDelay: 0

=== Sensor 17 ==
Name: Significant Motion Detector
Vendor: QTI
Version: 0x2
Handle: 0x36
Type: 17
maxRange: 1.0
resolution: 1.0
power: 0.399993 mA
minDelay: -1

=== Sensor 18 ==
Name: Game Rotation Vector
Vendor: QTI
Version: 0x2
Handle: 0x39
Type: 15
maxRange: 1.0
resolution: 0.0
power: 3.599990 mA
minDelay: 5000

=== Sensor 19 ==
Name: GeoMagnetic Rotation Vector
Vendor: QTI
Version: 0x2
Handle: 0x3c
Type: 20
maxRange: 1.0
resolution: 0.0
power: 5.399993 mA
minDelay: 16666

=== Sensor 20 ==
Name: Orientation
Vendor: QTI
Version: 0x2
Handle: 0x38
Type: 3
maxRange: 360.0
resolution: 0.100000
power: 8.599990 mA
minDelay: 5000

=== Sensor 21 ==
Name: Tilt Detector
Vendor: QTI
Version: 0x1
Handle: 0x3e
Type: 22
maxRange: 1.0
resolution: 1.0
power: 0.100000 mA
minDelay: 0

=== Sensor 22 ==
Name: Heart Rate Monitor
Vendor: QTI
Version: 0x2
Handle: 0x40
Type: 21
maxRange: 1.0
resolution: 1.0
power: 0.399993 mA
minDelay: 0

=== Sensor 23 ==
Name: Gravity -Wakeup Secondary
Vendor: QTI
Version: 0x2
Handle: 0x45
Type: 9
maxRange: 19.613296
resolution: 0.595
power: 3.599990 mA
minDelay: 5000

=== Sensor 24 ==
Name: Linear Acceleration -Wakeup Secondary
Vendor: QTI
Version: 0x2
Handle: 0x46
Type: 10
maxRange: 19.613296
resolution: 0.595
power: 3.599990 mA
minDelay: 5000

=== Sensor 25 ==
Name: Rotation Vector -Wakeup Secondary
Vendor: QTI
Version: 0x2
Handle: 0x47
Type: 11
maxRange: 1.0
resolution: 0.0
power: 8.599990 mA
minDelay: 5000

=== Sensor 26 ==
Name: Step Detector -Wakeup Secondary
Vendor: QTI
Version: 0x2
Handle: 0x4a
Type: 18
maxRange: 1.0
resolution: 1.0
power: 0.399993 mA
minDelay: 0

=== Sensor 27 ==
Name: Step Counter -Wakeup Secondary
Vendor: QTI
Version: 0x2
Handle: 0x4b
Type: 19
maxRange: 1.0
resolution: 1.0
power: 0.399993 mA
minDelay: 0

=== Sensor 28 ==
Name: Game Rotation Vector -Wakeup Secondary
Vendor: QTI
Version: 0x2
Handle: 0x48
Type: 15
maxRange: 1.0
resolution: 0.0
power: 3.599990 mA
minDelay: 5000

=== Sensor 29 ==
Name: GeoMagnetic Rotation Vector -Wakeup Secondary
Vendor: QTI
Version: 0x2
Handle: 0x49
Type: 20
maxRange: 1.0
resolution: 0.0
power: 5.399993 mA
minDelay: 16666

=== Sensor 30 ==
Name: Orientation -Wakeup Secondary
Vendor: QTI
Version: 0x2
Handle: 0x44
Type: 3
maxRange: 360.0
resolution: 0.100000
power: 8.599990 mA
minDelay: 5000

=== Sensor 31 ==
Name: Heart Rate Monitor -Wakeup Secondary
Vendor: QTI
Version: 0x2
Handle: 0x4f
Type: 21
maxRange: 1.0
resolution: 1.0
power: 0.399993 mA
minDelay: 0

=== Sensor 32 ==
Name: Wrist Tilt Gesture
Vendor: LGE
Version: 0x1
Handle: 0x43
Type: 26
maxRange: 1.0
resolution: 0.100000
power: 1.0 mA
minDelay: 0
</code></pre></details>

<details><summary><code>sensorapi-test</code></summary><pre><code>
********* Start testing of ClientApiTest *********
Config: Using QtTest library 5.15.3, Qt 5.15.3 (arm-little_endian-ilp32-eabi-hardfloat shared (dynamic) release build; by GCC 11.3.0), asteroid 1.1-nightly
QDEBUG : ClientApiTest::initTestCase() true
PASS   : ClientApiTest::initTestCase()
PASS   : ClientApiTest::testAccelerometerSensor()
PASS   : ClientApiTest::testGyroscopeSensor()
PASS   : ClientApiTest::testOrientationSensor()
QDEBUG : ClientApiTest::testRotationSensor() Z-axis rotation calculations in use: true
PASS   : ClientApiTest::testRotationSensor()
QDEBUG : ClientApiTest::testTapSensor() Requested sensor id ' "tapsensor" ' interface not granted
FAIL!  : ClientApiTest::testTapSensor() 'sensorIfc && sensorIfc->isValid()' returned FALSE. (Failed to get session)
   Loc: [../../../git/tests/client/clientapitest.cpp(343)]
PASS   : ClientApiTest::testMagnetometerSensor()
FAIL!  : ClientApiTest::testCompassSensor() 'sensorIfc->declinationValue() == 50' returned FALSE. ()
   Loc: [../../../git/tests/client/clientapitest.cpp(308)]
QDEBUG : ClientApiTest::testALSSensor() Requested sensor id ' "alssensor" ' interface not granted
FAIL!  : ClientApiTest::testALSSensor() 'sensorIfc && sensorIfc->isValid()' returned FALSE. (Failed to get session)
   Loc: [../../../git/tests/client/clientapitest.cpp(382)]
QDEBUG : ClientApiTest::testProximitySensor() Requested sensor id ' "proximitysensor" ' interface not granted
FAIL!  : ClientApiTest::testProximitySensor() 'sensorIfc && sensorIfc->isValid()' returned FALSE. (Failed to get session)
   Loc: [../../../git/tests/client/clientapitest.cpp(410)]
QDEBUG : ClientApiTest::testCommonAdaptorPipeline() Orientation sensor started, waiting for 250 ms.
QDEBUG : ClientApiTest::testCommonAdaptorPipeline() Accelerometer sensor started, waiting for 250 ms.
QDEBUG : ClientApiTest::testCommonAdaptorPipeline() Orientation sensor stopped, waiting for 250 ms.
QDEBUG : ClientApiTest::testCommonAdaptorPipeline() Orientation sensor destroyed, waiting for 250 ms.
QDEBUG : ClientApiTest::testCommonAdaptorPipeline() Accelerometer sensor stopped.
PASS   : ClientApiTest::testCommonAdaptorPipeline()
PASS   : ClientApiTest::testSessionInitiation()
QDEBUG : ClientApiTest::testBuffering() "magnetometersensor"  started, waiting for  1200  ms.
FAIL!  : ClientApiTest::testBuffering() 'frameCount == frameLimit * (i + 1)' returned FALSE. (Buffering err magnetometersensor (10 Hz): 0 == 1)
   Loc: [../../../git/tests/client/clientapitest.cpp(553)]
PASS   : ClientApiTest::testBufferingAllIntervalRanges()
QDEBUG : ClientApiTest::testBufferingCompatibility() "magnetometersensor"  started, waiting for  1500  ms.
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  1  in  964  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  2  in  3  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  3  in  1  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  4  in  1  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  5  in  1  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  6  in  1  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  7  in  1  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  8  in  1  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  9  in  1  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  10  in  1  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() "magnetometersensor"  started, waiting for  1100  ms.
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  1  in  1090  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  2  in  3  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  3  in  2  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  4  in  2  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  5  in  2  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  6  in  2  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  7  in  2  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  8  in  0  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  9  in  1  ms
QDEBUG : ClientApiTest::testBufferingCompatibility() dataAvailable()  10  in  0  ms
PASS   : ClientApiTest::testBufferingCompatibility()
QDEBUG : ClientApiTest::testBufferingInterval() "magnetometersensor"  started, waiting for  4800  ms.
QDEBUG : ClientApiTest::testBufferingInterval() frameAvailable():  40  in  3904  ms
QDEBUG : ClientApiTest::testBufferingInterval() "magnetometersensor"  started, waiting for  2800  ms.
QDEBUG : ClientApiTest::testBufferingInterval() frameAvailable():  30  in  2162  ms
PASS   : ClientApiTest::testBufferingInterval()
PASS   : ClientApiTest::testAvailableBufferIntervals()
PASS   : ClientApiTest::testAvailableBufferSizes()
QDEBUG : ClientApiTest::testDownsampling() "magnetometersensor"  started, waiting for  2500  ms.
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  1  in  53  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  2  in  101  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  3  in  99  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  4  in  100  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  5  in  101  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  6  in  99  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  7  in  104  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  8  in  100  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  9  in  100  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  10  in  100  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  1  in  930  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  11  in  103  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  12  in  99  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  13  in  100  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  14  in  100  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  15  in  100  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  16  in  100  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  17  in  100  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  18  in  100  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  19  in  100  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  20  in  100  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  2  in  1001  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  21  in  95  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  22  in  101  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  23  in  101  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  24  in  100  ms
QDEBUG : ClientApiTest::testDownsampling() dataAvailable()  25  in  101  ms
PASS   : ClientApiTest::testDownsampling()
QDEBUG : ClientApiTest::testDownsamplingDisabled() "magnetometersensor"  started, waiting for  2200  ms.
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  1  in  0  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  1  in  0  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  2  in  96  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  2  in  95  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  3  in  101  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  3  in  102  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  4  in  102  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  4  in  101  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  5  in  101  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  5  in  102  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  6  in  102  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  6  in  101  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  7  in  96  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  7  in  96  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  8  in  102  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  8  in  102  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  9  in  101  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  9  in  101  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  10  in  102  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  10  in  104  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  11  in  98  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  11  in  97  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  12  in  96  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  12  in  96  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  13  in  102  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  13  in  102  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  14  in  102  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  14  in  101  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  15  in  102  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  15  in  102  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  16  in  95  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  16  in  95  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  17  in  101  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  17  in  102  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  18  in  102  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  18  in  101  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  19  in  102  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  19  in  103  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  20  in  96  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  20  in  95  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  21  in  103  ms
QDEBUG : ClientApiTest::testDownsamplingDisabled() dataAvailable()  21  in  104  ms
PASS   : ClientApiTest::testDownsamplingDisabled()
PASS   : ClientApiTest::cleanupTestCase()
Totals: 16 passed, 5 failed, 0 skipped, 0 blacklisted, 18699ms
********* Finished testing of ClientApiTest *********
</code></pre></details>

**Comment by eLtMosen** [comment]
Mine have been since long time. Only ever flashed nightlies and never encountered not working sensors on lenok.

**Comment by GeckoEidechse** [comment]
> Any news on this issues state? My watches sensors are working
> 
> Are @GeckoEidechse problems resolved (somewhere else)?

Nope, though I haven't attempted flashing back WearOS yet to update my lenok's firmware.

**Comment by GeckoEidechse** [comment]
Solved my particular issue in #159

**Comment by eLtMosen** [comment]
Guess its time to close both issues then?

**Comment by MagneFire** [comment]
No, I think we should update our website. Only after that has been done close the issues.

**Comment by eLtMosen** [comment]
> No, I think we should update our website. Only after that has been done close the issues.

Agreed ;)
