### ISSUE TITLE
[catfish] Heart Rate not working

### ISSUE THREAD

**Issue by frankenstein91** [AsteroidOS/meta-smartwatch#69]
Contrary to the documentation on the website, measuring the heart rate does not work.
The load bar in the corresponding app moves, but unfortunately no measurement is performed and not even the LED at the bottom of the watch is turned on.

**Comment by MagneFire** [comment]
Can you clarify if you are using the 2018 (catfish) or 2020 (catfish_ext) variant?
Recently, we updated the sensor firmware to fix sensors (heart rate, tilt-to-wake, compass) on the 2020 version. It's possible that this lead to things breaking for the 2018 version.

**Comment by frankenstein91** [comment]
I am not sure when I bought the watch. But the bootloader only says catfish.

**Comment by frankenstein91** [comment]
After installing the file nanohub.full.catshark.19061201.bin from @MagneFire, the problem is solved.

(I think until the next update)

**Comment by frankenstein91** [comment]
log of `journalctl --no-pager`
[log.log](https://github.com/AsteroidOS/meta-smartwatch/files/8405281/log.log)

maybe also usefull for https://github.com/AsteroidOS/meta-smartwatch/issues/71 and https://github.com/AsteroidOS/meta-smartwatch/issues/70

**Comment by abhinavmarwaha** [comment]
> After installing the file nanohub.full.catshark.19061201.bin from @MagneFire, the problem is solved.
> 
> (I think until the next update)

How to do that exactly? I installed the one from website, in that it doesn't work.

**Comment by frankenstein91** [comment]
> How to do that exactly?

copy & past via SCP and than a reboot of the watch

**Comment by abhinavmarwaha** [comment]
> > How to do that exactly?
> 
> copy & past via SCP and than a reboot of the watch

where can I find this file?

**Comment by sevmonster** [comment]
New user, I do not have this issue on the latest nightly. Heart rate sensor works fine.

**Comment by eLtMosen** [comment]
Agreed, double checked on my catfish, works fine. Closing, feel free to reopen or make a new issue when the problem should arise again.
