### ISSUE TITLE
Support for oppo watch international version

### ISSUE THREAD

**Issue by wannaphong** [AsteroidOS/meta-smartwatch#77]
I found it can unlock oem with latest update and I found source code kernel.
![](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/VybxCNzewsKyCkxtYAJKmacI)
![](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/CQlKrGdvKAVMFrZvoBbWlKCC)

source code kernel https://android.googlesource.com/kernel/msm/+/refs/heads/android-msm-beluga-4.9-pie-wear-mr2

**Comment by iot-resister** [comment]
Can I update the docs for this?

**Comment by wannaphong** [comment]
The real installation is working!

**Comment by nelikp222** [comment]
Thank you for this work
both of you @wannaphong and @MagneFire 
is it safe to install now?
And any stock rom i can download incase of anything?

**Comment by wannaphong** [comment]
> Thank you for this work both of you @wannaphong and @MagneFire is it safe to install now? And any stock rom i can download incase of anything?

You can download the stock rom of oppo watch from Google. I can't upload to you becasue legal requirements. It's `.ofp` and can use https://github.com/bkerler/oppo_decrypt for find the stock rom.

**Comment by wannaphong** [comment]
I closed this issues because all list support are done by @MagneFire. Thank you!
